In [1]:
import torch
import numpy as np

In [3]:
# empty tensor
x = torch.empty(3)
print(x)

tensor([5.9694e-39, 9.2755e-39, 1.0561e-38])


In [4]:
# empty tensor
x = torch.empty((3, 5))
print(x)

tensor([[8.9081e-39, 9.1837e-39, 9.6429e-39, 9.8266e-39, 1.0194e-38],
        [1.0745e-38, 9.2755e-39, 8.4489e-39, 1.0561e-38, 1.0469e-38],
        [8.4490e-39, 1.0102e-38, 9.2755e-39, 9.5511e-39, 8.4490e-39]])


In [5]:
x = torch.rand((2, 2))
x

tensor([[0.5955, 0.1621],
        [0.2852, 0.8156]])

In [7]:
torch.zeros((2, 2))

tensor([[0., 0.],
        [0., 0.]])

In [8]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [10]:
x = torch.ones((2, 2), dtype=torch.int)
print(x.dtype)

torch.int32


In [11]:
x.size()

torch.Size([2, 2])

In [12]:
# tensor from data
x = torch.tensor([
    [2.1, 1.1],
    [4.3, 5.3]
])

x

tensor([[2.1000, 1.1000],
        [4.3000, 5.3000]])

## Basic operations with tensor

In [13]:
x = torch.rand((2, 2))
y = torch.rand((2, 2))

print(x)
print(y)

tensor([[0.0624, 0.4148],
        [0.1313, 0.9666]])
tensor([[0.1042, 0.9282],
        [0.4499, 0.4547]])


In [14]:
z = x+y
z

tensor([[0.1666, 1.3430],
        [0.5812, 1.4213]])

In [15]:
torch.add(x, y)

tensor([[0.1666, 1.3430],
        [0.5812, 1.4213]])

In [16]:
# inplace addtion
y.add_(x)
y

tensor([[0.1666, 1.3430],
        [0.5812, 1.4213]])

- in pytorch every function with trailing underscore will do an inplace opearation

In [17]:
z - x - y

tensor([[-0.0624, -0.4148],
        [-0.1313, -0.9666]])

In [18]:
torch.sub(x, y)

tensor([[-0.1042, -0.9282],
        [-0.4499, -0.4547]])

In [19]:
torch.mul(x, y)

tensor([[0.0104, 0.5571],
        [0.0763, 1.3738]])

In [21]:
torch.div(x, y)

tensor([[0.3747, 0.3089],
        [0.2259, 0.6801]])

## Slicing operations

In [23]:
x = torch.rand((5, 3))
print(x)

tensor([[0.4212, 0.0831, 0.5512],
        [0.9037, 0.2429, 0.9965],
        [0.1223, 0.5851, 0.7166],
        [0.9507, 0.6425, 0.9382],
        [0.5485, 0.4953, 0.3085]])


In [24]:
x[:, 0]

tensor([0.4212, 0.9037, 0.1223, 0.9507, 0.5485])

In [26]:
x[1:, 1:]

tensor([[0.2429, 0.9965],
        [0.5851, 0.7166],
        [0.6425, 0.9382],
        [0.4953, 0.3085]])

## Reshaping tensor

In [28]:
x = torch.rand((4, 4))
x

tensor([[0.6456, 0.9839, 0.9789, 0.0396],
        [0.0453, 0.6991, 0.3943, 0.6873],
        [0.6816, 0.2868, 0.6217, 0.1185],
        [0.3838, 0.8105, 0.1956, 0.4069]])

In [29]:
x.view(16)

tensor([0.6456, 0.9839, 0.9789, 0.0396, 0.0453, 0.6991, 0.3943, 0.6873, 0.6816,
        0.2868, 0.6217, 0.1185, 0.3838, 0.8105, 0.1956, 0.4069])

In [30]:
x.reshape(-1)

tensor([0.6456, 0.9839, 0.9789, 0.0396, 0.0453, 0.6991, 0.3943, 0.6873, 0.6816,
        0.2868, 0.6217, 0.1185, 0.3838, 0.8105, 0.1956, 0.4069])

## tensor to numpy conversion

In [37]:
import torch
import numpy as np

x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

In [38]:
y = x.numpy()
y

array([1., 1., 1., 1., 1.], dtype=float32)

- the converted tensor will share the same memory location
    - gpu/cpu

In [42]:
# example
# double the x tensor that will double the y array

x += 1
print(x)

print(y)

tensor([3., 3., 3., 3., 3.])
[1. 1. 1. 1. 1.]


- in this case it is not in the same memory location

In [40]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [41]:
a += 1

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


- here the elements share the meomory location

In [45]:
# for GPU operations
if torch.cuda.is_available():
    device = torch.device('cuda')
    
    x = torch.ones(5, device=device) # create a tensor in the gpu
    
    y = torch.ones(5)
    y = y.to(device) # allocate tenor y to gpu
    
    # to move tensor back to cpu
    y = y.to('cpu')

## requires_grad
- specify gradient need to be calculated

In [48]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)